# Objetos

Firebase: {
  style: {
    border-radius: 6
    font-size: 30
  }
}

Aplicativo: {
  style: {
    border-radius: 6
    font-size: 30
  }
}

Middleware: {
  style: {
    border-radius: 6
    font-size: 30
  }
}

Backend: {
  style: {
    border-radius: 6
    font-size: 30
  }
}



# Relacionamentos

Aplicativo -> Middleware: Registrar\n login {
  style: {
    font-size: 25
    bold: true
  }
}

Middleware -> Firebase: Criar\n usuário {
  style: {
    font-size: 25
    bold: true
  }
}

Firebase -> Middleware: Confirmação de\n usuário criado {
  style: {
    font-size: 25
    bold: true
  }
}

Middleware -> Backend: Pré-cadastro {
  style: {
    font-size: 25
    bold: true
  }
}

Middleware -> Aplicativo: Logar e prosseguir\n com o cadastro {
  style: {
    font-size: 25
    bold: true
  }
}

Aplicativo -> Firebase: Efetua o\n login {
  style: {
    font-size: 25
    bold: true
  }
}

Aplicativo -> Middleware: Cadastro\n de usuário {
  style: {
    font-size: 25
    bold: true
  }
}

Middleware -> Backend: Finalizar\n cadastrao {
  style: {
    font-size: 25
    bold: true
  }
}
